### ISSUE TITLE
Vim chooses ledger syntax instead of ledger_x for time tracking

### ISSUE THREAD

**Issue by colindean** [rcaputo/vim-ledger_x#2] opened 2018-08-17 15:12 UTC
I'm not quite sure what I've setup incorrectly that causes my time tracking ledger files not to be syntax-highlighted with `ledger_x` but with `ledger` instead. 

My plug config:

https://github.com/colindean/hejmo/blob/60009397508122426465e67f4f23272ae6545755/dotfiles/vim/bundles.vim#L46-L47

My vimrc:

https://github.com/colindean/hejmo/blob/master/dotfiles/vimrc

I tried adding 
```vim
autocmd BufNewFile,BufRead *.ledger set syntax=ledger_x
```
to my vimrc but it didn't help. Money ledger files seem to autoselect ledger_x just fine.

**Comment by rcaputo** [comment] 2018-08-17 17:09
The autocmd in ftdetect/ledger_x.vim is a little more complicated than the one you've posted:

`autocmd BufReadPost *.ldg,*.ledger setlocal filetype=ledger | setlocal syntax=ledger_x | compiler ledger`

If I recall, the BufReadPost causes the ledger_x syntax to be set after ledger sets its own.

I've never used Plug nor tested ledger_x with it.  It's plausible that Plug might not be handling ledger_x's underscore.  See `help: ftplugin-name` for the rule about underscores in plugin names.

**Comment by rcaputo** [comment] 2020-05-23 22:25
Thank you for taking the time to report this issue.  I appreciate your concern and collaboration.

Regrettably, I don't intend to resolve it as it currently stands.

I haven't encountered the problem myself, but I neither use plug, nor plan to.  This isn't because I have an opinion about plug but rather my current setup works well enough that I'm not inclined to change it.

ledger_x uses normal, documented vim features.  Until proven otherwise I assume that a contraindication with plug isn't ledger_x's fault.  I expect then that resolving this would require me to debug a module I have no experience with---a task I'm not motivated to undertake.

Also, so far this doesn't seem to be a general or widespread problem.  I can't tell whether the conflict is intrinsic to one or both modules or is caused by a co-interaction with a particular .vimrc.  For example, the reporter's previously mentioned `autocmd` that is different from the one included in ledger_x.

Therefore I'm closing this issue given its uncertain provenance and lack of progress.  This needn't be the final word on this issue.  I'm not opposed to reconsidering my decision if new information arises.

**Closed as completed by rcaputo** 2020-05-23 22:25 UTC
Labels: bug, help wanted, question

**Comment by alerque** [comment] 2020-05-24 07:48
"Help wanted" bugs that you don't plan to fix are still bugs ... and the issue reports should be left _open_ for tracking until resolved. Closed bug reports are not easily discoverable and send the wrong message when you do find them. You don't have to fix everything yourself, but if you actually want contributions closing the bug reports isn't the way to get them.

**Comment by rcaputo** [comment] 2020-05-24 22:40
You statements make a good point in an objective context.  I feel however that in the current situation they may not apply.  This should be obvious.  After all, I closed the issue.

I don't doubt there was a bug somewhere 1.75 years ago, but it wasn't proven to be in ledger_x, and there's no way of knowing whatever was broken hasn't been fixed by now.

I could have justifiably used the "invalid" and "wontfix" labels instead, but it was and remains my intent to fix ledger_x if the problem can be confirmed.  The labels I used instead may seem paradoxical since the issue is closed, but I feel they better express my intent should someone find this in the future.  Hopefully the labels and my comments at the time will encourage someone to reopen the issue if necessary.

If the problem recurs but the issue can't be found, I expect that sooner or later a new one will be opened.  That's also a fine outcome.
